# Generated by Django 4.2.15 on 2024-09-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.CharField(max_length=100)),
                ('applicant', models.CharField(max_length=200)),
                ('facility_type', models.CharField(max_length=100)),
                ('cnn', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('blocklot', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('permit', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('food_items', models.TextField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('schedule', models.TextField()),
                ('dayshours', models.CharField(max_length=255)),
                ('noi_sent', models.CharField(max_length=100)),
                ('approved', models.CharField(max_length=100)),
                ('prior_permit', models.CharField(max_length=100)),
                ('expiration_date', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('fire_prevention_districts', models.CharField(max_length=100)),
                ('police_districts', models.CharField(max_length=100)),
                ('supervisor_districts', models.CharField(max_length=100)),
                ('zip_codes', models.CharField(max_length=100)),
                ('neighborhoods_old', models.CharField(max_length=255)),
            ],
        ),
    ]
